name: Build Rockchip-FFmpeg
on: workflow_dispatch

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build Rockchip-FFmpeg
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk-Space
        run: df -h && sudo apt-get clean && docker system prune -a -f && sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc && df -h
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: .github/buildkit.toml
          driver: docker
      - name: Get download cache key
        id: dl_cache
        run: |
          echo "dltagname=$(./util/get_dl_cache_tag.sh)" >> $GITHUB_OUTPUT
      - name: Cache
        uses: actions/cache/restore@v4
        with:
          path: .cache/downloads
          key: download-cache-${{ steps.dl_cache.outputs.dltagname }}
          restore-keys: |
            download-cache-
      - name: Build Image
        run: ./makeimage.sh linuxarm64 gpl 6.1-rk
      - name: Build ffmpeg
        run: ./build.sh linuxarm64 gpl 6.1-rk
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linuxarm64-gpl-6.1-rk
          overwrite: true
          path: artifacts/*
